### ISSUE TITLE
[BUG] Whoogle spits out garbage when going to next page of search results

### ISSUE THREAD

**Issue by Rowan-Bird** [benbusby/whoogle-search#250]
Whenever i try to go to the next page of a search (e.g. COVID-19) it spits out a ton of garbage

The exact string is the following
gAAAAABgZPRDBmNckg-txy85CufwUIccaLrnLWvW7gm9lyPJAXd8uFW1bFln-rKIyC3QxQAkoMDGjcZDgNlEtAS5_Kluz1OpGg==

It's the same no matter what search i do

1. Search something
2. Go to the next page
3. See garbage in search bar

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [=] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [=] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 Ultimate 64-bit
 - Browser Google Chrome
 - Version 89

**Additional context**
Issues always occur

**Comment by benbusby** [comment]
Thanks for reporting. I just pushed a fix for this, feel free to update your instance using the `develop` or `heroku-app-beta` branches, or the `beta` or `buildx-experimental` docker images (once the CI build finishes).

**Comment by Rowan-Bird** [comment]
I'm actually using pip

**Comment by benbusby** [comment]
Okay, the pip package will be updated in the next day or so.

**Comment by Rowan-Bird** [comment]
I saw the new pip package, installed it, and can you believe, it was fi...

Nothing changed, other than the version number, new pip package, i typed
"pip install --upgrade whoogle-search" it reported that a newer version was
found, it uninstall 0.3.1 and installed 0.3.2, and i confirmed it, but the
bug wasn't fixed, unless that's gonna be for 0.4, but i doubt it, and to be
fair, i am using python 3.6 on Windows 7 SP1, but i also doubt that's the
issue, i can only think that this whole thing is suspicious, your code is
crap, or nobody has fixed it, or python sucks, i don't know

**Comment by Rowan-Bird** [comment]
Turns out, my antivirus was interfering, i moved whoogle search to the
trusted application list, and wouldn't you believe it, it worked just fine
(I am still on 0.3.2)
