### ISSUE TITLE
Whoogle search has a permanent unhealty status in Portainer

### ISSUE THREAD

**Issue by wiebereu** [benbusby/whoogle-search#272]
Since a couple of days after an update of the image i notice that the Whoogle container has a unhealty status in Portainer. 
I search the log and i found this kind of error messages: 

**INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file",
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0005),
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file",
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0004),
INFO:stem:Error while receiving a control message (SocketClosed): received exception "[Errno 9] Bad file descriptor",
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0004),
INFO:stem:Error while receiving a control message (SocketClosed): received exception "[Errno 9] Bad file descriptor",
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file",**

I tried to fix it by pulling the image again but to no avail. You can reach the container though. The only thing is the unhealty statys and the error messages. 
I am running Docker on a Synology NAS. 

**Describe the bug**

**To Reproduce**

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benbusby** [comment]
Which image are you using? I just pushed a change to `latest` and `beta` that should disable the error messages you were seeing. Can you try pulling the latest image to see if that helps?

**Comment by wiebereu** [comment]
I will try it and i will let you know of the results

**Comment by wiebereu** [comment]
I pulled the latest release and i don't see the error messages anymore in the log but the container stays unhealthy. 
this is the information from the logs: 
    
**Starting tor daemon...done.
Serving on http://0.0.0.0:5000**

I hope you don't suppress the error messages but that the problem was actually solved, cause disabling is not the same as solving.

**Comment by benbusby** [comment]
Well duh. I disabled the error messages from the stem library because they're overly verbose and aren't indicative of an actual problem. They've been around since Tor was integrated into the project, and have never shown to be linked to any errors. I got tired of users sending me the error logs over email, GitHub issues, etc and having to explain this every time, so now they're gone. 

I'll look into why you're still seeing the unhealthy message. I can't replicate in my own Portainer environment, so I'll have to try something else later.

**Comment by r0arkin** [comment]
FWIW, I too get an "unhealthy" status all the time. I even went as far as cloning your git repo and running docker-compose on it to make sure it wasn't my yaml, and I'm still seeing "unhealthy". Logs don't show much either.

**Comment by benbusby** [comment]
Can either of you try running:

```
docker inspect --format "{{json .State.Health }}" <container name>
```

**Comment by r0arkin** [comment]
Sure, here is mine:

```
{"Status":"unhealthy","FailingStreak":3,"Log":[{"Start":"2021-04-09T20:25:54.697077194-07:00","End":"2021-04-09T20:25:55.383872137-07:00","ExitCode":1,"Output":"index.html: Permission denied\nCannot write to ‘index.html’ (Permission denied).\n"},{"Start":"2021-04-09T20:26:25.885549387-07:00","End":"2021-04-09T20:26:26.116638293-07:00","ExitCode":1,"Output":"index.html: Permission denied\nCannot write to ‘index.html’ (Permission denied).\n"},{"Start":"2021-04-09T20:26:56.71000216-07:00","End":"2021-04-09T20:26:56.923652082-07:00","ExitCode":1,"Output":"index.html: Permission denied\nCannot write to ‘index.html’ (Permission denied).\n"}]}
```

**Comment by benbusby** [comment]
Thanks, that's super helpful. I'll push a fix shortly.

**Comment by benbusby** [comment]
Should be fixed in the `latest` and `beta` images once the build finishes.

**Comment by wiebereu** [comment]
Thank you! I'm looking forward to it.
