### ISSUE TITLE
[BUG] Last commit broke 'latest' Docker tag

### ISSUE THREAD

**Issue by th0mcat** [benbusby/whoogle-search#540]
**Describe the bug**
Last update to the `latest` docker image broke everything

```
$ docker logs -f whoogle
Starting tor daemon...done.
Requirement already satisfied: pip in ./venv/lib/python3.8/site-packages (21.1.1)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
Successfully installed pip-21.3.1
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Starting tor daemon...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
Starting tor daemon...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/whoogle/app/__init__.py", line 1, in <module>
    from app.filter import clean_query
  File "/whoogle/app/filter.py", line 2, in <module>
    from app.request import VALID_PARAMS, MAPS_URL
  File "/whoogle/app/request.py", line 1, in <module>
    from app.models.config import Config
  File "/whoogle/app/models/config.py", line 1, in <module>
    from app.utils.misc import read_config_bool
  File "/whoogle/app/utils/misc.py", line 1, in <module>
    from flask import Request
ModuleNotFoundError: No module named 'flask'
```

**Comment by Mio3000** [comment]
i can confirm this issue

**Comment by scgf** [comment]
Same here. I reverted to 0.6.0. I had auto-restart enabled and woke up to 187 email notofications telling me Whoogle had unexpectedly stopped. I know it's my fault for using Watchtower to auto-update!

**Comment by eddydc** [comment]
Watchtower also updated Whoogle over here and it resulted in a non working Whoogle. Portainer says - for the first time - even indicates it's running (with green).

**Comment by nakoo** [comment]
I don't have this issue when using `docker-compose`. I'm using latest version of `docker` and `docker-compose`. I think it only happens when using docker command line.



```bash
user@host:~$ docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

user@host:~$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

user@host:~$ docker-compose images
    Container                 Repository              Tag       Image Id       Size  
-------------------------------------------------------------------------------------
watchtower          containrrr/watchtower            latest   dd78a816fb76   16.42 MB
whoogle-search      benbusby/whoogle-search          latest   469da250e507   244.9 MB


user@host:~$ docker-compose logs whoogle-search
Attaching to whoogle-search
whoogle-search    | Nov 20 13:20:15.862 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.
whoogle-search    | Nov 20 13:20:15.862 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
whoogle-search    | Nov 20 13:20:15.867 [notice] Read configuration file "/etc/tor/torrc".
whoogle-search    | Nov 20 13:20:15.869 [notice] Opening Socks listener on 127.0.0.1:9050
whoogle-search    | Nov 20 13:20:15.869 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
whoogle-search    | Nov 20 13:20:15.869 [notice] Opening Control listener on 127.0.0.1:9051
whoogle-search    | Nov 20 13:20:15.869 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
whoogle-search    | Nov 20 13:20:15.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
whoogle-search    | Nov 20 13:20:17.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
whoogle-search    | Nov 20 13:20:19.000 [notice] Bootstrapped 0% (starting): Starting
whoogle-search    | Nov 20 13:20:19.000 [notice] Starting with guard context "default"
whoogle-search    | Nov 20 13:20:20.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
whoogle-search    | Nov 20 13:20:20.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
whoogle-search    | Nov 20 13:20:22.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
whoogle-search    | Nov 20 13:20:22.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
whoogle-search    | Nov 20 13:20:38.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
whoogle-search    | Nov 20 13:20:38.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
whoogle-search    | Nov 20 13:20:41.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
whoogle-search    | Nov 20 13:20:41.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
whoogle-search    | Nov 20 13:20:41.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6256, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
whoogle-search    | Nov 20 13:20:41.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6256, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
whoogle-search    | Nov 20 13:20:43.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
whoogle-search    | Nov 20 13:20:45.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
whoogle-search    | Nov 20 13:20:46.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
whoogle-search    | Nov 20 13:20:47.000 [notice] Bootstrapped 61% (loading_descriptors): Loading relay descriptors
whoogle-search    | Nov 20 13:21:17.000 [notice] Bootstrapped 66% (loading_descriptors): Loading relay descriptors
whoogle-search    | Nov 20 13:21:19.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
whoogle-search    | Nov 20 13:21:20.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
whoogle-search    | Nov 20 13:21:20.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
whoogle-search    | Nov 20 13:21:21.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
whoogle-search    | Nov 20 13:21:21.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
whoogle-search    | Nov 20 13:21:22.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
whoogle-search    | Nov 20 13:21:22.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
whoogle-search    | Nov 20 13:21:24.000 [notice] Bootstrapped 100% (done): Done
whoogle-search    | Nov 20 13:21:52.000 [notice] New control connection opened from 127.0.0.1.
whoogle-search    | Nov 20 13:21:52.000 [notice] Heartbeat: Tor's uptime is 0:01 hours, with 8 circuits open. I've sent 403 kB and received 3.01 MB. I've received 1 connections on IPv4 and 0 on IPv6. I've made 7 connections with IPv4 and 0 with IPv6.
whoogle-search    | Nov 20 13:21:52.000 [notice] While bootstrapping, fetched this many bytes: 516609 (consensus network-status fetch); 26774 (authority cert fetch); 2370797 (microdescriptor fetch)
whoogle-search    | Serving on http://0.0.0.0:5000
```

**Comment by th0mcat** [comment]
> I don't have this issue when using `docker-compose`. I'm using latest version of `docker` and `docker-compose` on Ubuntu.
> 
> ```shell
> user@host:~$ docker version
> Client: Docker Engine - Community
>  Version:           20.10.11
>  API version:       1.41
>  Go version:        go1.16.9
>  Git commit:        dea9396
>  Built:             Thu Nov 18 00:37:06 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.11
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.9
>   Git commit:       847da18
>   Built:            Thu Nov 18 00:35:15 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.12
>   GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
>  runc:
>   Version:          1.0.2
>   GitCommit:        v1.0.2-0-g52b36a2
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> ```shell
> user@host:~$ docker-compose version
> docker-compose version 1.29.2, build 5becea4c
> docker-py version: 5.0.0
> CPython version: 3.7.10
> OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
> ```
> 
> ```shell
> user@host:~$ docker-compose images
>     Container                 Repository              Tag       Image Id       Size  
> -------------------------------------------------------------------------------------
> watchtower          containrrr/watchtower            latest   dd78a816fb76   16.42 MB
> whoogle-search      benbusby/whoogle-search          latest   469da250e507   244.9 MB
> ```
> 
> ```shell
> user@host:~$ docker-compose logs whoogle-search
> Attaching to whoogle-search
> whoogle-search    | Nov 20 13:20:15.862 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.
> whoogle-search    | Nov 20 13:20:15.862 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
> whoogle-search    | Nov 20 13:20:15.867 [notice] Read configuration file "/etc/tor/torrc".
> whoogle-search    | Nov 20 13:20:15.869 [notice] Opening Socks listener on 127.0.0.1:9050
> whoogle-search    | Nov 20 13:20:15.869 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
> whoogle-search    | Nov 20 13:20:15.869 [notice] Opening Control listener on 127.0.0.1:9051
> whoogle-search    | Nov 20 13:20:15.869 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
> whoogle-search    | Nov 20 13:20:15.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
> whoogle-search    | Nov 20 13:20:17.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
> whoogle-search    | Nov 20 13:20:19.000 [notice] Bootstrapped 0% (starting): Starting
> whoogle-search    | Nov 20 13:20:19.000 [notice] Starting with guard context "default"
> whoogle-search    | Nov 20 13:20:20.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
> whoogle-search    | Nov 20 13:20:20.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
> whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
> whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
> whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
> whoogle-search    | Nov 20 13:20:22.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
> whoogle-search    | Nov 20 13:20:22.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
> whoogle-search    | Nov 20 13:20:38.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
> whoogle-search    | Nov 20 13:20:38.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
> whoogle-search    | Nov 20 13:20:41.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
> whoogle-search    | Nov 20 13:20:41.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
> whoogle-search    | Nov 20 13:20:41.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6256, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
> whoogle-search    | Nov 20 13:20:41.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6256, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
> whoogle-search    | Nov 20 13:20:43.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
> whoogle-search    | Nov 20 13:20:45.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
> whoogle-search    | Nov 20 13:20:46.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
> whoogle-search    | Nov 20 13:20:47.000 [notice] Bootstrapped 61% (loading_descriptors): Loading relay descriptors
> whoogle-search    | Nov 20 13:21:17.000 [notice] Bootstrapped 66% (loading_descriptors): Loading relay descriptors
> whoogle-search    | Nov 20 13:21:19.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
> whoogle-search    | Nov 20 13:21:20.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
> whoogle-search    | Nov 20 13:21:20.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
> whoogle-search    | Nov 20 13:21:21.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
> whoogle-search    | Nov 20 13:21:21.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
> whoogle-search    | Nov 20 13:21:22.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
> whoogle-search    | Nov 20 13:21:22.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
> whoogle-search    | Nov 20 13:21:24.000 [notice] Bootstrapped 100% (done): Done
> whoogle-search    | Nov 20 13:21:52.000 [notice] New control connection opened from 127.0.0.1.
> whoogle-search    | Nov 20 13:21:52.000 [notice] Heartbeat: Tor's uptime is 0:01 hours, with 8 circuits open. I've sent 403 kB and received 3.01 MB. I've received 1 connections on IPv4 and 0 on IPv6. I've made 7 connections with IPv4 and 0 with IPv6.
> whoogle-search    | Nov 20 13:21:52.000 [notice] While bootstrapping, fetched this many bytes: 516609 (consensus network-status fetch); 26774 (authority cert fetch); 2370797 (microdescriptor fetch)
> whoogle-search    | Serving on http://0.0.0.0:5000
> ```

You should do a manual `docker pull benbusby/whoogle:latest`

**Comment by AzamServer** [comment]
I can also confirm that this bug is present in the latest version

**Comment by scgf** [comment]
I use docker-compose and with the 'latest' image the container keeps restarting. If I specify 0.6.0 all is well. I am using docker 20.10.3 and docker-compose version 1.28.5. I run docker on my Synology NAS so have no option to instal later versions until they are made available to me. Given **every** other docker container works fine and Whoogle did until just this one version, I do not think it has anything to do with the versions of docker or docker-compose I am running.

**Comment by nakoo** [comment]
> > I don't have this issue when using `docker-compose`. I'm using latest version of `docker` and `docker-compose` on Ubuntu.
> > ```shell
> > user@host:~$ docker version
> > Client: Docker Engine - Community
> >  Version:           20.10.11
> >  API version:       1.41
> >  Go version:        go1.16.9
> >  Git commit:        dea9396
> >  Built:             Thu Nov 18 00:37:06 2021
> >  OS/Arch:           linux/amd64
> >  Context:           default
> >  Experimental:      true
> > 
> > Server: Docker Engine - Community
> >  Engine:
> >   Version:          20.10.11
> >   API version:      1.41 (minimum version 1.12)
> >   Go version:       go1.16.9
> >   Git commit:       847da18
> >   Built:            Thu Nov 18 00:35:15 2021
> >   OS/Arch:          linux/amd64
> >   Experimental:     false
> >  containerd:
> >   Version:          1.4.12
> >   GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
> >  runc:
> >   Version:          1.0.2
> >   GitCommit:        v1.0.2-0-g52b36a2
> >  docker-init:
> >   Version:          0.19.0
> >   GitCommit:        de40ad0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > user@host:~$ docker-compose version
> > docker-compose version 1.29.2, build 5becea4c
> > docker-py version: 5.0.0
> > CPython version: 3.7.10
> > OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > user@host:~$ docker-compose images
> >     Container                 Repository              Tag       Image Id       Size  
> > -------------------------------------------------------------------------------------
> > watchtower          containrrr/watchtower            latest   dd78a816fb76   16.42 MB
> > whoogle-search      benbusby/whoogle-search          latest   469da250e507   244.9 MB
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > user@host:~$ docker-compose logs whoogle-search
> > Attaching to whoogle-search
> > whoogle-search    | Nov 20 13:20:15.862 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.
> > whoogle-search    | Nov 20 13:20:15.862 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
> > whoogle-search    | Nov 20 13:20:15.867 [notice] Read configuration file "/etc/tor/torrc".
> > whoogle-search    | Nov 20 13:20:15.869 [notice] Opening Socks listener on 127.0.0.1:9050
> > whoogle-search    | Nov 20 13:20:15.869 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
> > whoogle-search    | Nov 20 13:20:15.869 [notice] Opening Control listener on 127.0.0.1:9051
> > whoogle-search    | Nov 20 13:20:15.869 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
> > whoogle-search    | Nov 20 13:20:15.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
> > whoogle-search    | Nov 20 13:20:17.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
> > whoogle-search    | Nov 20 13:20:19.000 [notice] Bootstrapped 0% (starting): Starting
> > whoogle-search    | Nov 20 13:20:19.000 [notice] Starting with guard context "default"
> > whoogle-search    | Nov 20 13:20:20.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
> > whoogle-search    | Nov 20 13:20:20.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
> > whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
> > whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
> > whoogle-search    | Nov 20 13:20:21.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
> > whoogle-search    | Nov 20 13:20:22.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
> > whoogle-search    | Nov 20 13:20:22.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
> > whoogle-search    | Nov 20 13:20:38.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
> > whoogle-search    | Nov 20 13:20:38.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
> > whoogle-search    | Nov 20 13:20:41.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
> > whoogle-search    | Nov 20 13:20:41.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
> > whoogle-search    | Nov 20 13:20:41.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6256, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
> > whoogle-search    | Nov 20 13:20:41.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6256, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
> > whoogle-search    | Nov 20 13:20:43.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
> > whoogle-search    | Nov 20 13:20:45.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
> > whoogle-search    | Nov 20 13:20:46.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
> > whoogle-search    | Nov 20 13:20:47.000 [notice] Bootstrapped 61% (loading_descriptors): Loading relay descriptors
> > whoogle-search    | Nov 20 13:21:17.000 [notice] Bootstrapped 66% (loading_descriptors): Loading relay descriptors
> > whoogle-search    | Nov 20 13:21:19.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
> > whoogle-search    | Nov 20 13:21:20.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
> > whoogle-search    | Nov 20 13:21:20.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
> > whoogle-search    | Nov 20 13:21:21.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
> > whoogle-search    | Nov 20 13:21:21.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
> > whoogle-search    | Nov 20 13:21:22.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
> > whoogle-search    | Nov 20 13:21:22.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
> > whoogle-search    | Nov 20 13:21:24.000 [notice] Bootstrapped 100% (done): Done
> > whoogle-search    | Nov 20 13:21:52.000 [notice] New control connection opened from 127.0.0.1.
> > whoogle-search    | Nov 20 13:21:52.000 [notice] Heartbeat: Tor's uptime is 0:01 hours, with 8 circuits open. I've sent 403 kB and received 3.01 MB. I've received 1 connections on IPv4 and 0 on IPv6. I've made 7 connections with IPv4 and 0 with IPv6.
> > whoogle-search    | Nov 20 13:21:52.000 [notice] While bootstrapping, fetched this many bytes: 516609 (consensus network-status fetch); 26774 (authority cert fetch); 2370797 (microdescriptor fetch)
> > whoogle-search    | Serving on http://0.0.0.0:5000
> > ```
> 
> You should do a manual `docker pull benbusby/whoogle:latest`

You're right. It also happens to me. I guess my watchtower didn't update my images.

**Comment by tweek11** [comment]
Same situation here - Watchdog updated Portainer and now currently receiving the same errors - Notice it shows started but the assigned ports are not showing up - When restarting the container they quickly show listed and then disappear with the same error - Tried to recreate and pull the latest version manually in Portainer and same issue repeats itself ModuleNotFoundError: No module named 'flask'

**Comment by AzamServer** [comment]
I manually updated the image using docker pull and made the container using docker-compose, but I'm still getting the error.

**Comment by eddydc** [comment]
> I use docker-compose and with the 'latest' Whoogle image the container keeps restarting. If I specify 0.6.0 all is well. I am using docker 20.10.3 and docker-compose version 1.28.5. I run docker on my Synology NAS so have no option to install later versions until they are made available to me. Given **every** other docker container works fine and Whoogle did until just this one version, I do not think it has anything to do with the versions of docker or docker-compose I am running.

I'm also using whoogle via a docker container on a synology nas with portainer/watchtower. I assume when a release has been tagged as latest, it has been tested and one doesn't need check an reinstall other releases in order to get it working again. Otherwise watchtower has no use.

**Comment by scgf** [comment]
We can't make that assumption. Occasionally a broken release does get through. This is the first time it has ever happened to me, but there are dire warnings about allowing auto-updates all over the place. I weighed up the risk and feel the convenience outweighs the disadvantage. My NAS is only used by me and I'm running nothing critical so if I need to change a docker-compose.yml to point to a previous release once in a couple of years I'm fine.

**Comment by Afaren57** [comment]
Hi, I had the same problem while updating. I tried to uninstall completely and reinstall it with docker-compose, now it is stuck to this error and restart the process indefinitely : 
`Error: [Errno 13] Permission denied: '/whoogle/venv',
Nov 20 16:29:11.097 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.,
Nov 20 16:29:11.097 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning,
Nov 20 16:29:11.097 [notice] Read configuration file "/etc/tor/torrc".,
Nov 20 16:29:11.101 [notice] Opening Socks listener on 127.0.0.1:9050,
Nov 20 16:29:11.101 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050,
Nov 20 16:29:11.101 [notice] Opening Control listener on 127.0.0.1:9051,
Nov 20 16:29:11.101 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051,
Nov 20 16:29:11.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.,
Nov 20 16:29:11.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.,
Nov 20 16:29:11.000 [notice] Bootstrapped 0% (starting): Starting,
Nov 20 16:29:11.000 [notice] Starting with guard context "default",
Error: [Errno 13] Permission denied: '/whoogle/venv',
Nov 20 16:30:04.255 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.,
Nov 20 16:30:04.255 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning,
Nov 20 16:30:04.255 [notice] Read configuration file "/etc/tor/torrc".,
Nov 20 16:30:04.259 [notice] Opening Socks listener on 127.0.0.1:9050,
Nov 20 16:30:04.259 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050,
Nov 20 16:30:04.259 [notice] Opening Control listener on 127.0.0.1:9051,
Nov 20 16:30:04.259 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051,
Nov 20 16:30:04.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.,
Nov 20 16:30:04.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.,
Nov 20 16:30:04.000 [notice] Bootstrapped 0% (starting): Starting,
Nov 20 16:30:04.000 [notice] Starting with guard context "default",
Error: [Errno 13] Permission denied: '/whoogle/venv'`

I'll try reverting to 0.6.0

**Comment by nakoo** [comment]
It seems this issue can be fixed by adding `source venv/bin/activate` in `run` file. I didn't test but have similar experience about this bug.

**Comment by Afaren57** [comment]
> 

I totally don't know how to add anything in run file, I'm a bit of a noob with docker xD

**Comment by nakoo** [comment]
> > 
> 
> I totally don't know how to add anything in run file, I'm a bit of a noob with docker xD

No, You need to build the image yourself. I can do PR but needs some test. I'm installing docker on my machine, but it takes a while since I'm running Gentoo...

**Comment by DanielVolz** [comment]
> Hi, I had the same problem while updating. I tried to uninstall completely and reinstall it with docker-compose, now it is stuck starting the boostrap and retries indefinitely. After reverting to 0.6.0, no problem, bootstrap load normally. Here is part of the logs pulling the latest one :
> 
> ```
> Nov 20 16:29:11.097 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.,
> Nov 20 16:29:11.097 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning,
> Nov 20 16:29:11.097 [notice] Read configuration file "/etc/tor/torrc".,
> Nov 20 16:29:11.101 [notice] Opening Socks listener on 127.0.0.1:9050,
> Nov 20 16:29:11.101 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050,
> Nov 20 16:29:11.101 [notice] Opening Control listener on 127.0.0.1:9051,
> Nov 20 16:29:11.101 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051,
> Nov 20 16:29:11.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.,
> Nov 20 16:29:11.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.,
> Nov 20 16:29:11.000 [notice] Bootstrapped 0% (starting): Starting,
> Nov 20 16:29:11.000 [notice] Starting with guard context "default",
> Error: [Errno 13] Permission denied: '/whoogle/venv',
> Nov 20 16:30:04.255 [notice] Tor 0.4.5.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.,
> Nov 20 16:30:04.255 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning,
> Nov 20 16:30:04.255 [notice] Read configuration file "/etc/tor/torrc".,
> Nov 20 16:30:04.259 [notice] Opening Socks listener on 127.0.0.1:9050,
> Nov 20 16:30:04.259 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050,
> Nov 20 16:30:04.259 [notice] Opening Control listener on 127.0.0.1:9051,
> Nov 20 16:30:04.259 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051,
> Nov 20 16:30:04.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.,
> Nov 20 16:30:04.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.,
> Nov 20 16:30:04.000 [notice] Bootstrapped 0% (starting): Starting,
> Nov 20 16:30:04.000 [notice] Starting with guard context "default",
> Error: [Errno 13] Permission denied: '/whoogle/venv'```
> ```

I have the exact same issue with the newest version.

**Comment by eddydc** [comment]
Why is this issue closed? Is there a solution? It is still not working on my side.

**Comment by bruvv** [comment]
because it is fixed but not yet been pushed

**Comment by milesmcclane** [comment]
Sorry to be a pain, but this issue doesn’t seem to be fixed for me. How exactly do I ensure that the docker image is updated to the latest? Do I need to rebuild the container?

**Comment by benbusby** [comment]
@milesmcclane you could try removing and re-pulling the image. I'm not sure why that's sometimes necessary, but I know some users have had to do that before.

**Comment by th0mcat** [comment]
This still isn't fixed.

Should I just clone the repo and bind mount `requirements.txt`
