### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by 0xspade** [benbusby/whoogle-search#686]
In my environment variable, I specify to replace Wikipedia with wikiless (`WHOOGLE_ALT_WIKI="wikiless.org"`), other alternative social medias are working except for wikipedia. If I attempt to search `wiki <some keyword>` the results are from `en.wikipedia.org` and it should be `wikiless`, right?

**Comment by benbusby** [comment]
Yep, looks like it was attempting to replace `*wikipedia.com` links, not `*wikipedia.org`. Fixed now -- thanks!

**Comment by 0xspade** [comment]
Is this updated in docker too?

**Comment by benbusby** [comment]
Yeah, should be updated on the `latest` tag

**Comment by 0xspade** [comment]
Just updated my whoogle docker now, and still can't see `wikiless` if I search `wiki <some keyword>`. My environment variable is `WHOOGLE_CONFIG_ALTS=1` but I delete the `WHOOGLE_ALT_WIKI="wikiless.org"`. Should be working, right?

![image](https://user-images.githubusercontent.com/18681023/159623341-6974017a-9f13-4100-bda3-e6c28f945bad.png)

**Comment by benbusby** [comment]
Hmm, that's odd. If you go to your home page config menu, is the `Replace Social Media Links` option checked? I'm wondering if there's an issue with enabling `WHOOGLE_CONFIG_ALTS` within the container.

**Comment by 0xspade** [comment]
`WHOOGLE_CONFIG_ALTS` was set to `1`. Other SC links are working fine, except on Wikipedia. However, on Instagram, I always needed to add `u` while searching a profile. Example: `instagram <some profile>`, there will be outputs, click a link. After clicking, it will say `page not found` e.g.:`https://bibliogram.pussthecat.org/blowupdogecoin?hl=en` but if you add `u`, e.g.: `https://bibliogram.pussthecat.org/u/blowupdogecoin?hl=en` you will successfully view the profile.
