### ISSUE TITLE
[BUG] Cannot set search to 'any language'

### ISSUE THREAD

**Issue by totti4ever** [benbusby/whoogle-search#73]
**Describe the bug**
After setting the language in the config to German the results are always in German, I cannot go back to 'any language', it just flips back to German.

**To Reproduce**
1. Search
2. Set langauge to `any language`
3. See that it's still set to German

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83

**Comment by benbusby** [comment]
Fixed by 3dbe51e9e7b4fe7a140ecf286007130d595a5302. All language configuration should be handled by the Whoogle search home page from now on, the config card on the results page was a leftover element that should've been removed. The Docker Hub image should be updated shortly. Thanks for reporting!

**Comment by totti4ever** [comment]
@benbusby thanks for the quick response and fix. But I am somewhat disappointed, since I am having two main use cases:
1. private stuff --> searching for German results
2. tech stuff --> mainly looking on English website, e.g. reddit or github

Problem now is, I have to decide and switch based on the decision the main configuration. I thought, it was a really good solution to offer the selection of primary language only and all languages in the results page. What were your intentions of removing it?

**Comment by benbusby** [comment]
The language switcher you were referring to originally never worked in the first place, it was a leftover element of the UI that needed to be removed to avoid confusion. Adding in the functionality you’re seeking would be an entirely separate feature, which I’m happy to add. I’ll create an issue for it shortly.

**Comment by beyondbytes** [comment]
This issue was not solved. I have the same issue here using the latest docker image.
